const config = 
{ api_root: "http://localhost:9090/api/",
    rmri_indexes: [
        { name: "טלוויזיה - קשת", 
          value: 43, 
          color: "green",
          group: "main" },
        { name: "טלוויזיה - רשת", 
          value: 23, 
          color: "green",
          group: "main" },
        { name: "טלוויזיה - ערוץ 10", 
          value: 28, 
          color: "green",
          group: "main" },

        { name: "Google Adwords", 
          value: 54, 
          color: "yellow",
          group: "main" },
        { name: "Facebook", 
          value: 143, 
          color: "yellow",
          group: "main" },
        { name: "Youtube", 
          value: 3, 
          color: "yellow",
          group: "main" },
        { name: "Banners", 
          value: 5, 
          color: "yellow",
          group: "main" },
        { name: "Outbrain/Taboola", 
          value: 2, 
          color: "yellow",
          group: "main" },
        { name: "Remarketing", 
          value: 12, 
          color: "yellow",
          group: "main" },

        { name: "שילוט חוצות", 
          value: 23, 
          color: "blue",
          group: "main" },
        { name: "חסויות", 
          value: -2, 
          color: "blue",
          group: "main" },
        { name: "עיתונות מודפסות", 
          value: 2, 
          color: "blue",
          group: "main" },

        { name: "קריאיטיב: זמרות", 
          value: 32, 
          color: "beige",
          group: "additional" },
        { name: "קריאיטיב: שף מפורסם", 
          value: 18, 
          color: "beige",
          group: "additional" },
        { name: "קמפיין קריאטיב: מסר ישיר", 
          value: 7, 
          color: "beige",
          group: "additional" },
        { name: "קמפיין מתחרים", 
          value: -25, 
          color: "beige",
          group: "additional" },
        { name: "משתנים נוספים", 
          value: 4, 
          color: "beige",
          group: "additional" },
    ]
       
     };

module.exports = config;